In [1]:
import pandas as pd
import nepali_roman as nr

In [2]:
df1= pd.read_csv('../Data/ss_ac_at_txt_unbal.csv')
df1.head()

,0,GENERAL,जोगाउन को लागि,गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा बने को छाया सेन्टर जस्ता लाई जोगाउन को लागि ल्याउदैछ विधेक ।
0,1,GENERAL,लखेटनु पछ,दले ले देश सकेछन सबै बेचे र खान सुरू गरेछन अब ...
1,1,GENERAL,ससकृती ध्वस्त पार्ने,नेपाल को ससकृती ध्वस्त पार्ने योजना हो यो !
2,1,GENERAL,भुमाफिया,मठ मन्दिर गुम्बा का जग्गा हरु मा भुमाफिया को न...
3,1,GENERAL,बेची सके,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...
4,1,GENERAL,बेची खाने नियत,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...

In [3]:
df1.columns

Index(['0', 'GENERAL', 'जोगाउन को लागि',
       'गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा बने को छाया सेन्टर जस्ता लाई जोगाउन को लागि ल्याउदैछ विधेक ।'],
      dtype='object')

In [4]:
df2 = pd.DataFrame(columns=['Polarity', 'Sentiment', 'Aspect Term', 'Text'])
df2.head()

Empty DataFrame
Columns: [Polarity, Sentiment, Aspect Term, Text]
Index: []

In [5]:
df2.loc[len(df1)] = df1.columns
df2 = df2.reset_index(drop=True)

df2.head()

,Polarity,Sentiment,Aspect Term,Text
0,0,GENERAL,जोगाउन को लागि,गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा...

In [6]:
df1= df1.rename(columns={'0':'Polarity', 'GENERAL':'Sentiment', 'जोगाउन को लागि':'Aspect Term', 'गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा बने को छाया सेन्टर जस्ता लाई जोगाउन को लागि ल्याउदैछ विधेक ।':'Text'})
df1.head()

,Polarity,Sentiment,Aspect Term,Text
0,1,GENERAL,लखेटनु पछ,दले ले देश सकेछन सबै बेचे र खान सुरू गरेछन अब ...
1,1,GENERAL,ससकृती ध्वस्त पार्ने,नेपाल को ससकृती ध्वस्त पार्ने योजना हो यो !
2,1,GENERAL,भुमाफिया,मठ मन्दिर गुम्बा का जग्गा हरु मा भुमाफिया को न...
3,1,GENERAL,बेची सके,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...
4,1,GENERAL,बेची खाने नियत,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...

In [7]:
df= pd.concat([df2,df1], ignore_index=True)
df.head()

,Polarity,Sentiment,Aspect Term,Text
0,0,GENERAL,जोगाउन को लागि,गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा...
1,1,GENERAL,लखेटनु पछ,दले ले देश सकेछन सबै बेचे र खान सुरू गरेछन अब ...
2,1,GENERAL,ससकृती ध्वस्त पार्ने,नेपाल को ससकृती ध्वस्त पार्ने योजना हो यो !
3,1,GENERAL,भुमाफिया,मठ मन्दिर गुम्बा का जग्गा हरु मा भुमाफिया को न...
4,1,GENERAL,बेची सके,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...

In [8]:

# Reorder columns
df = df[['Text', 'Aspect Term', 'Sentiment','Polarity']]
df.head()

,Text,Aspect Term,Sentiment,Polarity
0,गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा...,जोगाउन को लागि,GENERAL,0
1,दले ले देश सकेछन सबै बेचे र खान सुरू गरेछन अब ...,लखेटनु पछ,GENERAL,1
2,नेपाल को ससकृती ध्वस्त पार्ने योजना हो यो !,ससकृती ध्वस्त पार्ने,GENERAL,1
3,मठ मन्दिर गुम्बा का जग्गा हरु मा भुमाफिया को न...,भुमाफिया,GENERAL,1
4,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...,बेची सके,GENERAL,1

In [9]:
# Saving this dataset with after reordering columns

In [10]:
df.to_csv('../Data/Nepali_dataset.csv', index= False)

# Making a translated Dataset

In [11]:
df_translated = df.copy()
df_translated.head()

,Text,Aspect Term,Sentiment,Polarity
0,गुठी विधेक ल्याएर ठमेल मा राज गुठि को जग्गा मा...,जोगाउन को लागि,GENERAL,0
1,दले ले देश सकेछन सबै बेचे र खान सुरू गरेछन अब ...,लखेटनु पछ,GENERAL,1
2,नेपाल को ससकृती ध्वस्त पार्ने योजना हो यो !,ससकृती ध्वस्त पार्ने,GENERAL,1
3,मठ मन्दिर गुम्बा का जग्गा हरु मा भुमाफिया को न...,भुमाफिया,GENERAL,1
4,नेपाल का कल कर्खाना र नदि नाला बेची सके अब मठ ...,बेची सके,GENERAL,1

In [12]:
# Applying romanize_text to the 'Text' and 'Aspect Term' columns
df_translated['Text'] = df_translated['Text'].apply(nr.romanize_text)
df_translated['Aspect Term'] = df_translated['Aspect Term'].apply(nr.romanize_text)

df_translated.head()

,Text,Aspect Term,Sentiment,Polarity
0,guthi widheka lyaaera thamela maa raaja guthi ...,j0gaauna k0 laagi,GENERAL,0
1,dale le desa sakechhana sabai beche ra khaana ...,lakhetanu pachha,GENERAL,1
2,nepaala k0 sasakariti dhwasta paarne y0janaa h...,sasakariti dhwasta paarne,GENERAL,1
3,matha mandira gumbaa kaa jaggaa haru maa bhuma...,bhumaaphiyaa,GENERAL,1
4,nepaala kaa kala karkhaanaa ra nadi naalaa bec...,bechi sake,GENERAL,1

In [13]:
df_translated.to_csv('../Data/Nepali_dataset_romanized.csv',index=False)